// 猜歌王 — 42首粤语港乐完整曲库
// 每首歌包含：iTunes 30秒试听音频、600×600专辑封面、完整歌词、YouTube演唱视频片段

import { Song } from './supabase'

// YouTube video URLs — real IDs for popular songs, search embed fallback for others
const V = (id: string) => `https://www.youtube.com/embed/${id}`
// YouTube search embed — auto-plays first result for the query
const VS = (query: string) => `https://www.youtube.com/embed?listType=search&list=${encodeURIComponent(query)}`

export const CANTOPOP_LIBRARY: Song[] = [
  // ═══ Beyond 专场 ═══
  { id: '1', title: '海阔天空', artist: 'Beyond', composer: '黄家驹', lyricist: '黄家驹', genre: 'rock', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_01.m4a', audio_duration_sec: 30, theme: ['beyond', 'rock', 'classic'], year: 1993, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_01.jpg', video_url: V('V4GUy2EHMMs'), cover_gradient: ['#ff6b35', '#f7c59f'], lyrics: '今天我 寒夜里看雪飘过\n怀着冷却了的心窝漂远方\n风雨里追赶 雾里分不清影踪\n天空海阔你与我 可会变（谁没在变）\n\n多少次 迎着冷眼与嘲笑\n从没有放弃过心中的理想\n一刹那恍惚 若有所失的感觉\n不知不觉已变淡 心里爱（谁明白我）\n\n原谅我这一生不羁放纵爱自由\n也会怕有一天会跌倒\n背弃了理想 谁人都可以\n哪会怕有一天只你共我' },
  { id: '2', title: '光辉岁月', artist: 'Beyond', composer: '黄家驹', lyricist: '黄家驹', genre: 'rock', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_02.m4a', audio_duration_sec: 30, theme: ['beyond', 'rock', 'classic'], year: 1991, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_02.jpg', video_url: V('qu_FSptjRic'), cover_gradient: ['#f6d365', '#fda085'], lyrics: '钟声响起归家的讯号\n在他生命里 仿佛带点唏嘘\n黑色肌肤给他的意义\n是一生奉献 肤色斗争中\n\n年月把拥有变做失去\n疲倦的双眼带着期望\n今天只有残留的躯壳\n迎接光辉岁月 风雨中抱紧自由\n\n一生经过彷徨的挣扎\n自信可改变未来\n问谁又能做到' },
  { id: '3', title: '真的爱你', artist: 'Beyond', composer: '黄家驹', lyricist: '梁美薇', genre: 'rock', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_03.m4a', audio_duration_sec: 30, theme: ['beyond', 'rock', 'classic'], year: 1989, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_03.jpg', video_url: V('n8aK_IUna_Y'), cover_gradient: ['#a8edea', '#fed6e3'], lyrics: '无法可修饰的一对手\n带出温暖永远在背后\n纵使啰嗦始终关注\n不懂珍惜太内疚\n\n仍记起温馨的一对手\n始终给我照顾未变样\n理想今天终于等到\n分享光辉盼做到\n\n春风化雨暖透我的心\n一生眷顾无言地送赠\n是你多么温馨的目光\n教我坚毅望着前路\n叮嘱我跌倒不应放弃\n没法解释怎可报尽亲恩\n爱意宽大是无限\n请准我说声真的爱你' },
  { id: '32', title: '不再犹豫', artist: 'Beyond', composer: '黄家驹', lyricist: '梁美薇', genre: 'rock', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_32.m4a', audio_duration_sec: 30, theme: ['beyond', 'rock'], year: 1991, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_32.jpg', video_url: V('fKKgY7BXxJE'), cover_gradient: ['#ff9a9e', '#fecfef'], lyrics: '无聊望见了犹豫\n达到理想不太易\n即使有信心 斗志却抑制\n\n谁人定我去或留\n定我心中的宇宙\n只想靠两手 向理想挥手\n\n问句天几高 心中志比天更高\n自信打不死的心态活到老\n\nOH 我有我心底故事\n亲手写上每段 得失乐与悲与梦儿\nOH 纵有创伤不退避\n梦想有一天可找到梦中的日子' },
  { id: '33', title: '灰色轨迹', artist: 'Beyond', composer: '黄家驹', lyricist: '刘卓辉', genre: 'rock', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_33.m4a', audio_duration_sec: 30, theme: ['beyond', 'rock'], year: 1990, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_33.jpg', video_url: V('-PkuSuJOlfE'), cover_gradient: ['#667eea', '#764ba2'], lyrics: '酒一再沉溺 何时麻醉我抑郁\n经过了所有 没法子可再可回头\n心里没法子 控制自己的手\n想要去挽回 逝去的日子\n\n冲开心中愁闷 原来仍是你\n灰色轨迹 踏碎了多少梦\n不知不觉 已走到了尽头\n\n背弃了理想 谁人都可以\n哪会怕有一天只你共我\n此刻的我在何方 是你多么的想知' },
  { id: '34', title: '情人', artist: 'Beyond', composer: '黄家驹', lyricist: '刘卓辉', genre: 'rock', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_34.m4a', audio_duration_sec: 30, theme: ['beyond', 'rock'], year: 1993, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_34.jpg', video_url: V('kCSqwtZKNIk'), cover_gradient: ['#c471f5', '#fa71cd'], lyrics: '盼望你没有为我又再度暗中淌泪\n我不想留底 你的心空虚\n盼望你别再让我像背负太深的罪\n我的心如水 你不必痴醉\n\n哦 你可知 谁甘心离去\n哦 你可知 我的心碎\n\n是缘是情是童真 还是意外\n有泪有罪有付出 还有忍耐\n是人是墙是寒冬 藏在眼内\n有你有我有情有梦 原来是你' },

  // ═══ 陈奕迅专场 ═══
  { id: '9', title: '富士山下', artist: '陈奕迅', composer: 'Christopher Chak', lyricist: '林夕', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_09.m4a', audio_duration_sec: 30, theme: ['eason', 'classic'], year: 2006, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_09.jpg', video_url: V('ghnT1uOwfrY'), cover_gradient: ['#89f7fe', '#66a6ff'], lyrics: '拦路雨偏似雪花 饮泣的你冻吗\n这风褛我给你磨到有襟花\n连掉了渍也不怕 怎么始终牵挂\n苦心选中今天想车你回家\n\n原谅我不再送花 伤口应要结疤\n花瓣铺满心里坟场才害怕\n如若你非我不嫁 彼此终必火化\n一生一世等一天需要代价\n\n谁都只得那双手 靠拥抱亦难任你拥有\n要拥有必先懂失去怎接受\n曾沿着雪路浪游 为何为好事泪流\n谁能凭爱意要富士山私有' },
  { id: '10', title: 'K歌之王', artist: '陈奕迅', composer: '陈辉阳', lyricist: '林夕', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_10.m4a', audio_duration_sec: 30, theme: ['eason', 'classic'], year: 2000, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_10.jpg', video_url: VS('K歌之王 陈奕迅 MV'), cover_gradient: ['#c471f5', '#fa71cd'], lyrics: '我唱得不够动人 你别皱眉\n我愿意和你 约定至死\n只想嬉戏唱游 到下世纪\n请你别嫌我将这煽情 奉献给你\n\n我以为 要是唱的用心良苦\n你总会对我 有些在乎\n我以为 虽然爱的路途坎坷\n就此别过 也未算太差\n\n谁人又相信 一世一生这肤浅对白\n来吧送给你 叫几百万人流泪过的歌\n如从未听过 誓言如幸福摩天轮' },
  { id: '11', title: '浮夸', artist: '陈奕迅', composer: 'C.Y. Kong', lyricist: '黄伟文', genre: 'pop', difficulty: 'expert', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_11.m4a', audio_duration_sec: 30, theme: ['eason'], year: 2005, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_11.jpg', video_url: VS('浮夸 陈奕迅 MV'), cover_gradient: ['#ff9a9e', '#fecfef'], lyrics: '有人问我 我就会讲\n但是无人来\n我期待 到无奈 有话要讲\n得不到装载\n\n我的心情犹像樽盖 等被揭开\n嘴巴却在养青苔\n人潮内 愈文静 愈变得 不受理睬\n自己要搞出意外\n\n像突然 地高歌 任何地方也像开四面台\n着最闪的衫 扮十分感慨\n有人来拍照要记住插袋\n\n你当我是浮夸吧 夸张只因我很怕\n似木头 似石头的话 得到注意吗\n其实怕被忘记 至放大来演吧\n很不安 怎去优雅\n世上还赞颂沉默吗\n不够爆炸 怎么有话题 让我夸\n做大娱乐家' },
  { id: '12', title: '明年今日', artist: '陈奕迅', composer: '陈小霞', lyricist: '林夕', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_12.m4a', audio_duration_sec: 30, theme: ['eason', 'classic'], year: 2002, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_12.jpg', video_url: V('8NJVNkzhJM4'), cover_gradient: ['#feada6', '#f5efef'], lyrics: '若这一刻我竟严重痴呆\n根本不需要被爱\n永远在床上发梦\n余生再没有悲哀\n\n人若能够站不起来\n还有什么可以期待\n在有生的瞬间能遇到你\n竟花光所有运气\n\n到这日才发现\n曾呼吸过空气\n\n明年今日 别再要失眠\n床褥都改变 如果有幸会面\n或在同伴新婚的盛宴\n惶惑地等待你出现\n\n明年今日 未见你一年\n谁舍得改变 离开你六十年\n但愿能认得出你的子女\n临别亦听得到你讲再见' },
  { id: '35', title: '十面埋伏', artist: '陈奕迅', composer: '郭伟亮', lyricist: '黄伟文', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_35.m4a', audio_duration_sec: 30, theme: ['eason'], year: 2004, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_35.jpg', video_url: V('QGHB-5e37Fw'), cover_gradient: ['#48c6ef', '#6f86d6'], lyrics: '闻说你时常在下午 来这里寄信件\n全城在寻觅你 我却有幸先碰见\n差一点 你我就可遇见\n如像隔世 才相识一样\n\n从何时开始 害怕睁开眼\n没有你在旁 如独处一样\n\n十面埋伏过 爱你更寂寞\n十万个为何 不可解释清楚\n从来无人在意我 在你的身边经过\n原来从头未遇过' },
  { id: '36', title: '好久不见', artist: '陈奕迅', composer: '陈小霞', lyricist: '施立', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_36.m4a', audio_duration_sec: 30, theme: ['eason'], year: 2007, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_36.jpg', video_url: VS('好久不见 陈奕迅 MV'), cover_gradient: ['#a1c4fd', '#c2e9fb'], lyrics: '我来到 你的城市\n走过你来时的路\n想象着 没我的日子\n你是怎样的孤独\n\n拿着你 给的照片\n熟悉的那一条街\n只是没了你的画面\n我们回不到那天\n\n你会不会忽然的出现\n在街角的咖啡店\n我会带着笑脸 挥手寒暄\n和你 坐着聊聊天\n\n我多么想和你见一面\n看看你最近改变\n不再去说从前 只是寒暄\n对你说一句 只是说一句\n好久不见' },

  // ═══ 王菲专场 ═══
  { id: '13', title: '红豆', artist: '王菲', composer: '柳重言', lyricist: '林夕', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_13.m4a', audio_duration_sec: 30, theme: ['faye', 'classic'], year: 1998, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_13.jpg', video_url: V('5wmfXve11rM'), cover_gradient: ['#a18cd1', '#fbc2eb'], lyrics: '还没好好地感受 雪花绽放的气候\n我们一起颤抖 会更明白什么是温柔\n还没跟你牵着手 走过荒芜的沙丘\n可能从此以后 学会珍惜天长和地久\n\n有时候 有时候\n我会相信一切有尽头\n相聚离开 都有时候\n没有什么会永垂不朽\n\n可是我 有时候\n宁愿选择留恋不放手\n等到风景都看透\n也许你会陪我看细水长流' },
  { id: '14', title: '暧昧', artist: '王菲', composer: '陈小霞', lyricist: '林夕', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_14.m4a', audio_duration_sec: 30, theme: ['faye'], year: 1995, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_14.jpg', video_url: V('bR8u65g_t7o'), cover_gradient: ['#fa709a', '#fee140'], lyrics: '眉目里似哭不哭 还维持着笑容\n其实心中 淌着血泪\n情人知己 极矛盾的身份\n跟你相爱 没法公开\n\n徘徊在似苦又甜之间\n欲言又止的唇 流露了暖昧\n\n天灰灰 会不会\n让我忘了你是谁\n累不累 要不要\n这样暧昧的滋味\n\n也许应该 多一点点勇气\n也许应该 少一点点猜疑\n可偏偏 我和你\n只能维持这微妙的距离' },
  { id: '15', title: '容易受伤的女人', artist: '王菲', composer: '中岛美雪', lyricist: '潘源良', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_15.m4a', audio_duration_sec: 30, theme: ['faye', 'classic'], year: 1992, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_15.jpg', video_url: V('tDw_ULjZWA8'), cover_gradient: ['#f093fb', '#f5576c'], lyrics: '人渐醉 夜更深 令我不懂分假与真\n情难自禁 我却其实属于\n极度容易受伤的女人\n\n不要 不要 不要骤来骤去\n请珍惜我的心\n若你 真的 要我 伴着你\n请勿又再 不闻不问\n\n让我 终于 找到 倚靠\n让我 从此 不需 再飘渺\n愿你的爱 能像那 火焰燃烧\n在这冷夜 将我心 完全融掉' },
  { id: '37', title: '约定', artist: '王菲', composer: '陈小霞', lyricist: '林夕', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_37.m4a', audio_duration_sec: 30, theme: ['faye', 'classic'], year: 1997, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_37.jpg', video_url: VS('约定 王菲 MV'), cover_gradient: ['#96fbc4', '#f9f586'], lyrics: '还记得当天旅馆的门牌\n还留住笑着离开的神态\n当天整个城市 那样轻快\n沿路一起走半里长街\n\n还记得街灯照出一脸黄\n还燃亮那份微温的便当\n剪影的你轮廓太好看\n凝住眼泪才敢细看\n\n明日天地 只恐怕认不回自己\n仍未忘跟你约定 假如不会死\n就算你壮阔胸膛 不敌天气\n两鬓斑白都可认得你' },
  { id: '38', title: '暗涌', artist: '王菲', composer: '陈辉阳', lyricist: '林夕', genre: 'pop', difficulty: 'expert', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_38.m4a', audio_duration_sec: 30, theme: ['faye'], year: 1997, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_38.jpg', video_url: VS('暗涌 王菲 MV'), cover_gradient: ['#667eea', '#764ba2'], lyrics: '就算天空再深 看出裂痕\n眉头仍聚满密云\n就算一屋暗灯 照不穿我身\n仍可反映你心\n\n让这口烟跳升 我身躯下沉\n曾多么想可接近\n但缘份飘不定 似云像烟\n抓不到 却缠身\n\n仍然在暗涌中 即使不见面\n也暗中 有感觉\n像暗涌 像暗涌\n随时可以 淹没我' },

  // ═══ 粤语经典 ═══
  { id: '4', title: '红日', artist: '李克勤', composer: '立花里佳', lyricist: '李克勤', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_04.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1992, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_04.jpg', video_url: VS('红日 李克勤 MV'), cover_gradient: ['#ff0844', '#ffb199'], lyrics: '命运就算颠沛流离\n命运就算曲折离奇\n命运就算恐吓着你做人没趣味\n别流泪 心酸 更不应舍弃\n我愿能 一生永远陪伴你\n\n命运就算颠沛流离\n命运就算曲折离奇\n命运就算恐吓着你做人没趣味\n别流泪 心酸 更不应舍弃\n我愿能 一生永远陪伴你\n\n哦~ 一生之中兜兜转转 那会看清楚\n彷徨时我也试过独坐一角像是没协助\n在某年 那幼小的我\n也曾问过我的妈妈 这世界 为何有这么多坎坷' },
  { id: '5', title: '千千阙歌', artist: '陈慧娴', composer: '马饲野康二', lyricist: '林振强', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_05.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1989, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_05.jpg', video_url: V('4GFyzGJlPxg'), cover_gradient: ['#fbc2eb', '#a6c1ee'], lyrics: '徐徐回望 曾属于彼此的晚上\n红红仍是你 赠我的心中艳阳\n如流傻泪 祈望可体恤兼见谅\n明晨离别你 路也许孤单得漫长\n\n一瞬间 太多东西要讲\n可惜即将在各一方\n只好深深把这刻尽凝望\n\n来日纵是千千阙歌 飘于远方我路上\n来日纵是千千晚星 亮过今晚月亮\n都比不起这宵美丽 亦绝不可使我更欣赏\n因你今晚共我唱' },
  { id: '6', title: '人生何处不相逢', artist: '陈慧娴', composer: '罗大佑', lyricist: '简宁', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_06.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1988, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_06.jpg', video_url: V('ac3vmC_RrA0'), cover_gradient: ['#d4fc79', '#96e6a1'], lyrics: '随浪随风飘飘荡\n随着命运跌荡\n在这日这地 竟可与你重遇上\n如像做梦 何曾料到\n\n人生何处不相逢\n重逢在何年何月\n或者就在明天\n或者就在眼前\n\n谁令我 这一生\n兜兜转转 又再遇上\n是你 是你 令我心醉\n是你 是你 令我难忘' },
  { id: '7', title: '风继续吹', artist: '张国荣', composer: '宇崎竜童', lyricist: '郑国江', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_07.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1983, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_07.jpg', video_url: V('VamWdAd6Qig'), cover_gradient: ['#667eea', '#764ba2'], lyrics: '我劝你早点归去 你说你不想归去\n只叫我抱着你 静静看着你\n我见你眼中 有泪垂\n风继续吹 不忍远离\n\n心里极渴望 希望留下伴着你\n风继续吹 不忍远离\n心里亦有泪 不愿流泪望着你\n\n过去多少 快乐记忆\n何妨与你一起去追\n要将忧郁苦痛洗去\n柔情蜜意我愿记取\n要强忍离情泪 未许它向下流' },
  { id: '8', title: 'Monica', artist: '张国荣', composer: 'Nobody', lyricist: '黎彼得', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_08.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1984, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_08.jpg', video_url: V('w3N5tisg20I'), cover_gradient: ['#48c6ef', '#6f86d6'], lyrics: 'Monica 谁能代替你地位\n你以往教我教我的一切\n今天的一切\n我已知 不可再拥有\n\nMonica 谁能代替你地位\n你以爱我爱我的一切\n今天的一切\n我已不可再拥有\n\n当一切过去 情已不再\n但心中依然有你\n当一切过去 情已不再\nMonica 谁能代替你地位' },
  { id: '30', title: '傻女', artist: '陈慧娴', composer: 'Diego Hernandez', lyricist: '林振强', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_30.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1988, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_30.jpg', video_url: V('AlzUiZbbbJU'), cover_gradient: ['#fddb92', '#d1fdff'], lyrics: '每次我望向你 你亦望向我的时候\n我便觉得 这世界 还有温柔\n每次我望向你 你却不望向我的时候\n我便觉得 这世界 再没理由\n\n傻女 傻女\n为何仍然在等\n傻女 傻女\n为何仍不死心\n\n也许 我太傻\n也许 我太天真\n但我只想 与你 共度余生' },
  { id: '31', title: '飘雪', artist: '陈慧娴', composer: '桑田佳佑', lyricist: '简宁', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_31.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1991, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_31.jpg', video_url: V('oGTEVhr6-5E'), cover_gradient: ['#a1c4fd', '#c2e9fb'], lyrics: '又见雪飘过 飘于伤心记忆中\n让我再想你 却掀起我心痛\n早经分开了 为何热爱尚情重\n独过追忆岁月 或许此生不会懂\n\n又见雪飘过 飘于伤心记忆中\n让我再想你 却掀起我心痛\n早经分开了 为何热爱尚情重\n独过追忆岁月 或许此生不会懂\n\n原来是你令我 一生也改变' },
  { id: '21', title: '真的汉子', artist: '林子祥', composer: '林子祥', lyricist: '郑国江', genre: 'rock', difficulty: 'expert', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_21.m4a', audio_duration_sec: 30, theme: ['classic', 'rock'], year: 1988, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_21.jpg', video_url: VS('真的汉子 林子祥 MV'), cover_gradient: ['#ff6b35', '#f7c59f'], lyrics: '成和败努力尝试\n人若有志应该不怕迟\n谁人在我未为意\n成就靠真本事\n\n做个真的汉子\n承担起苦痛跟失意\n投入为我愿意\n全力干心中所事\n\n成和败努力尝试\n人若有志应该不怕迟\n谁人在我未为意\n成就靠真本事\n\n做个真的汉子\n承担起苦痛跟失意\n投入为我愿意\n全力干心中所事' },
  { id: '22', title: '一生何求', artist: '陈百强', composer: '王文清', lyricist: '潘伟源', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_22.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1989, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_22.jpg', video_url: V('jgECnV15V6M'), cover_gradient: ['#96fbc4', '#f9f586'], lyrics: '冷暖哪可休\n回头多少个秋\n寻遍了却偏失去\n未盼却在手\n\n我得到没有\n没法解释得失错漏\n刚刚听到望到便更改\n不知根源追究\n\n一生何求\n常判决放弃与拥有\n耗尽我这一生\n触不到已跑开\n\n一生何求\n迷惘里永远看不透\n没料到我所失的竟已是我的所有' },
  { id: '23', title: '浪子心声', artist: '许冠杰', composer: '许冠杰', lyricist: '许冠杰/黎彼得', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_23.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1976, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_23.jpg', video_url: V('PiLDj4hXvLI'), cover_gradient: ['#fbc2eb', '#a6c1ee'], lyrics: '难分真与假 人面多险诈\n几多有共享 荣华富贵怕\n\n天造之材 皆有其用\n振翅高飞 无须在梦中\n\n人比海里沙 毋用多牵挂\n君可见漫天落霞 名利息间似雾化\n\n命里有时终须有\n命里无时莫强求' },
  { id: '24', title: '半斤八两', artist: '许冠杰', composer: '许冠杰', lyricist: '许冠杰', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_24.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1976, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_24.jpg', video_url: VS('半斤八两 许冠杰 MV'), cover_gradient: ['#f6d365', '#fda085'], lyrics: '我哋呢班打工仔\n通街走籴直头系坏肠胃\n揾个些少到月底点够驶（奀过鬼）\n确系认真湿滞\n\n最弊波士郁啲发威（癫过鸡）\n一味喺处系唔系乱咁吠\n翳亲佢做到冇气\n冇计冇计\n\n半斤八两 就算点样扎起\n半斤八两 wet到粒粒皆辛苦' },
  { id: '25', title: '每天爱你多一些', artist: '张学友', composer: '桑田佳佑', lyricist: '林振强', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_25.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1991, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_25.jpg', video_url: V('aGZDE8ZpBWM'), cover_gradient: ['#a8edea', '#fed6e3'], lyrics: '曾共你相识当天 心已属你\n纵是分开 仍然念你\n无惧远隔百千里 就算几番风霜作预备\n未来如何未怕 一起可面对\n\n每天爱你多一些\n不必多说 一世跟你拖\n每天爱你多一些\n不必多说 一世跟你过\n\n曾共你相识当天 心已属你\n纵是分开 仍然念你\n无惧远隔百千里 就算几番风霜作预备\n未来如何未怕 一起可面对' },
  { id: '26', title: '吻别', artist: '张学友', composer: '殷文琦', lyricist: '何启弘', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_26.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1993, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_26.jpg', video_url: V('gP2fRq1bJhk'), cover_gradient: ['#c471f5', '#fa71cd'], lyrics: '前尘往事成云烟 消散在彼此眼前\n就连说过了再见 也看不见你有些哀怨\n给我的一切 你不过是在敷衍\n你笑的越甜美 我的心就越破碎\n\n总在刹那间 有一些了解\n说过的话不可能会实现\n就在一转眼 发现你的脸\n已经陌生不会再像从前\n\n我和你吻别 在无人的街\n让风痴笑我不能拒绝\n我和你吻别 在狂乱的夜\n我的心 等著迎接伤悲' },
  { id: '27', title: '只想一生跟你走', artist: '张学友', composer: '巫启贤', lyricist: '刘卓辉', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_27.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1993, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_27.jpg', video_url: VS('只想一生跟你走 张学友 MV'), cover_gradient: ['#feada6', '#f5efef'], lyrics: '只想一生跟你走\n共你有过最美的邂逅\n只想一生跟你走\n在这生中 伴你左右\n\n从前情信 仍然常翻\n当初的心事 从前的情诗\n只想一生跟你走\n在这生中 伴你左右\n\n只想一生跟你走\n共你有过最美的邂逅\n只想一生跟你走\n在这生中 伴你左右' },
  { id: '28', title: '夕阳之歌', artist: '梅艳芳', composer: '马饲野康二', lyricist: '陈少琪', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_28.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1989, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_28.jpg', video_url: V('XnNIPXT9YvE'), cover_gradient: ['#ff0844', '#ffb199'], lyrics: '斜阳无限 无奈只一息间灿烂\n随云霞渐散 逝去的光彩不复还\n迟迟年月 难耐这一生的变幻\n如浮云聚散 缠结这沧桑的倦颜\n\n漫长路 骤觉光阴退减\n欢欣总短暂未再返\n哪个看透我梦想是平淡\n\n曾遇上几多风雨翻\n编织我交错梦幻\n曾遇你真心的臂弯\n伴我走过患难' },
  { id: '29', title: '似水流年', artist: '梅艳芳', composer: '喜多郎', lyricist: '郑国江', genre: 'pop', difficulty: 'expert', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_29.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1984, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_29.jpg', video_url: V('gnYpl2Ef3f4'), cover_gradient: ['#f093fb', '#f5576c'], lyrics: '望着海一片 满怀倦 无泪也无言\n望着天一片 只感到情怀乱\n我的心又似小木船 远景不见\n但仍向着前\n\n谁在命里主宰我 好景不再常伴我\n每天挣扎 人海里\n\n似水流年 不可以留住昨天\n留下只有思念 一串串 永远缠\n浩瀚烟波里 我怀念 怀念往年\n外貌早改变 处境都变 情怀未变' },
  { id: '39', title: '讲不出再见', artist: '谭咏麟', composer: '赵容弼', lyricist: '向雪怀', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_39.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1994, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_39.jpg', video_url: V('1_rjE9BIQ1M'), cover_gradient: ['#4facfe', '#00f2fe'], lyrics: '是对是错也好 不必说了\n是怨是爱也好 不须揭晓\n何事更重要 比两心的需要\n柔情密意怎么可缺少\n\n是进是退也好 有若狂潮\n是痛是爱也好 不须发表\n曾为你愿意 我梦想都不要\n流言自此心知不会少\n\n最不舍得你 讲不出再见\n这段情 越是回忆 越是心痛' },
  { id: '40', title: '一生中最爱', artist: '谭咏麟', composer: '伍思凯', lyricist: '向雪怀', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_40.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1992, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_40.jpg', video_url: VS('一生中最爱 谭咏麟 MV'), cover_gradient: ['#fa709a', '#fee140'], lyrics: '如果痴痴的等某日终于可等到一生中最爱\n谁介意你我这段情每每碰上了意外不清楚未来\n何曾愿意 我心中所爱\n每天要孤单看海\n\n如果开开心心同游 是否可相恋到永久\n谁料到你我这段情 每每碰上了意外不清楚未来\n\n宁愿一生中 说话都不会谎\n我是你一生中最爱\n如真 可不分 可相伴 一世一双人' },
  { id: '41', title: '上海滩', artist: '叶丽仪', composer: '顾嘉辉', lyricist: '黄霑', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_41.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1980, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_41.jpg', video_url: VS('上海滩 叶丽仪 MV'), cover_gradient: ['#667eea', '#764ba2'], lyrics: '浪奔 浪流\n万里滔滔江水永不休\n淘尽了 世间事\n混作滔滔一片潮流\n\n是喜 是愁\n浪里分不清欢笑悲忧\n成功 失败\n浪里看不出有未有\n\n爱你恨你 问君知否\n似大江一发不收\n转千弯 转千滩\n亦未平复此中争斗\n\n又有喜 又有愁\n就算分不清欢笑悲忧\n仍愿翻 百千浪\n在我心中起伏够' },
  { id: '42', title: '万水千山总是情', artist: '汪明荃', composer: '顾嘉辉', lyricist: '邓伟雄', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_42.m4a', audio_duration_sec: 30, theme: ['classic'], year: 1982, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_42.jpg', video_url: VS('万水千山总是情 汪明荃 MV'), cover_gradient: ['#a8edea', '#fed6e3'], lyrics: '莫说青山多障碍\n风也急 风也劲\n白云过山峰也可传情\n莫说水中多变幻\n水也清 水也静\n柔情似水爱共永\n\n未怕罡风吹散了热爱\n万水千山总是情\n\n聚散也有天注定\n不怨天 不怨命\n但求有山水共作证' },

  // ═══ 新生港乐 ═══
  { id: '16', title: '喜欢你', artist: '邓紫棋', composer: '黄家驹', lyricist: '黄家驹', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_16.m4a', audio_duration_sec: 30, theme: ['new_gen', 'beyond'], year: 2014, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_16.jpg', video_url: V('4OqXWzekVw4'), cover_gradient: ['#4facfe', '#00f2fe'], lyrics: '喜欢你 那双眼动人 笑声更迷人\n愿再可 轻抚你 那可爱面容\n挽手说梦话 像昨天 你共我\n\n满带理想的我 曾经多冲动\n屡怨与她相爱难有自由\n愿你此刻可会知 是我衷心地说声\n\n喜欢你 那双眼动人 笑声更迷人\n愿再可 轻抚你 那可爱面容\n挽手说梦话 像昨天 你共我\n\n每晚夜里自我独行 随处坐下来\n再度想起你 可爱面容\n愿再可 轻抚你 那可爱面容' },
  { id: '17', title: '光年之外', artist: '邓紫棋', composer: '邓紫棋', lyricist: '邓紫棋', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_17.m4a', audio_duration_sec: 30, theme: ['new_gen'], year: 2016, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_17.jpg', video_url: V('nMfPqeZz2Nw'), cover_gradient: ['#a1c4fd', '#c2e9fb'], lyrics: '感受停在我发端的指尖\n如何瞬间冻结时间\n记住望着我坚定的双眼\n也许已经没有明天\n\n面对浩瀚的星海\n这一微小尘埃\n命运却要我们危难中相爱\n\n也许航道以外 是醒不来的梦\n乱世以外 是纯净的相拥\n我没想到 为了你 我能疯狂到\n山崩海啸 没有你 根本不想逃' },
  { id: '18', title: '我的骄傲', artist: '容祖儿', composer: '陈光荣', lyricist: '黄伟文', genre: 'pop', difficulty: 'beginner', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_18.m4a', audio_duration_sec: 30, theme: ['classic', 'new_gen'], year: 2003, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_18.jpg', video_url: VS('我的骄傲 容祖儿 MV'), cover_gradient: ['#96fbc4', '#f9f586'], lyrics: 'See me fly 我亦相信我的翅膀\n能飞得更高更远\nProud of you 我亦信你的双手\n可给我幸福温暖\n\nI can fly 我在天空高处飞翔\n今天终于找到方向\n终于可在天空中 找到\n我向往的光芒' },
  { id: '19', title: '心淡', artist: '容祖儿', composer: '陈光荣', lyricist: '黄伟文', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_19.m4a', audio_duration_sec: 30, theme: ['new_gen'], year: 2003, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_19.jpg', video_url: V('E4jPiazznkY'), cover_gradient: ['#fddb92', '#d1fdff'], lyrics: '很可惜 当初那些 甜蜜语言\n都变了 谎言 没法可避免\n心淡了 不想再算\n\n情 还是那么浅\n爱 还是那么远\n不想再 为你失眠\n心淡了 不想再算\n\n很可惜 当初那些 缠绵片段\n都变了 泡影 没法可再演\n心淡了 不想再算' },
  { id: '20', title: '大哥', artist: '卫兰', composer: '陈台证', lyricist: '林夕', genre: 'pop', difficulty: 'intermediate', audio_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/audio/cantopop_20.m4a', audio_duration_sec: 30, theme: ['new_gen'], year: 2005, artwork_url: 'https://orxenguwlhrgmbqyiyrk.supabase.co/storage/v1/object/public/covers/cantopop_20.jpg', video_url: VS('大哥 卫兰 MV'), cover_gradient: ['#ffecd2', '#fcb69f'], lyrics: '我要爱情不需要登对\n不需要你默许\n不需要你理会我的感受\n大哥 大哥 你算什么\n\n如果我是你大哥\n你是否会尊重我\n如果我是你大哥\n你是否会更爱我\n\n我要爱情不需要登对\n不需要你默许\n不需要你理会我的感受\n大哥 大哥 你算什么' },
]

export default CANTOPOP_LIBRARY
